
        var quizData = {
            "en": {
                "questions": [
                      
                    " Directions (Set of 7): Read the following passage carefully and answer the questions given below. Certain words are given in bold to help you locate them while answering some of the questions.<br> Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr> Which of the following facts are correct as per the given passage?<br>(I) The decrease in the cost of renewable energy resulted in its wide use.<br>(II) China massively supported solar power and became largest investor in renewable energy.<br>(III) Egypt is conducting feasibility studies for building largest solar power plant.", 
                    " Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr>What did the author mean by the line “The electricity sector remains the brightest spot for renewables with the exponential growth ofsolar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.”? <br>(I) The growth of renewable energy in electricity sector is not that impressive.<br>(II) Electric sector has performed the best for renewables.<br>(III) Hydropower generation has a significant contribution in the electricity sector.  ",
                    " Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr> Which of the following is/are the positive effect(s) of renewable energy?<br>(I) Overall increase in the global temperature.<br>(II) Carbon dioxide emissions were reduced to a considerable amount.<br>(III) Nile being converted into a biodiversity hotspot.  ",
                    " Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr>Why government subsidies are likely to become less important?  ", 
                    " Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr>Which of the following words will come in place of (A) as given in the passage?  ",
                    " Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr>Which of the following word is most similar in meaning to <b>“accounting for”</b> as given in the passage?  ",
                    "Renewable energy is the future, and future is finally here. Global investment in renewable energy shot up last year, far outstripping investment in fossil fuels, according to a UN report. As the price of clean energy technology <b>plummets</b>, it has become an increasingly attractive prospect for world governments. China was by far the world’s largest investor in renewable energy in 2017, <b>accounting for</b> nearly half of the new infrastructure commissioned. This was mainly a result of its massive support for solar power, which globally attracted nearly a fifth more investment than in the previous year. Other countries including Australia, Sweden and Mexico more than doubled the amount of money they pumped into clean energy projects. 'Yet again, this was a record year for new renewable power capacity being financed,' Francoise d’Estais from UNEnvironment’s energy and climate branch told The Independent. “We had a record 157 gigawatts commissioned last year, far outstripping the fossil fuel generating capacity, which we estimated as 70 gigawatts.” <br><br>                             In just over a decade, concerted investment has increased the proportion of world electricity generated by wind, solar and other renewable sources from around 5 per cent to 12 per cent. “The electricity sector remains the brightest spot for renewables with the exponential growth of solar photovoltaics and wind in recent years, and building on the significant contribution of hydropower generation.” But, electricity accounts for only a fifth of global energy consumption, and the role of renewables in the transportation and heating sectors remains ____(A)____ to the energy transition. The global replacement of traditional fuels with renewables led to around 1.8 gigatonnes of carbon dioxide emissions being avoided last year – the equivalent of removing the entire US transport system. According to the Wind and Solar Atlas, there are opportunities and potential for Wind and Solar plants in the East and West Nile areas that will produce around 31,150 MW from wind and 52,300 MW from solar. Egypt is also considering financing options to conduct feasibility studies for building the world largest solar power plant for both electricity generation and water desalination. <br>The UK has been performing well in clean energy generation, with recent figures showing wind and solar sources had overtaken nuclear as suppliers of electricity. However, despite these positive trends, 2017 saw a big drop of 65 per cent in British renewables investment.Experts have criticised the withdrawal of UK support for onshore wind, as previous analysis has demonstrated it already has the capacity to outcompete fossil fuels as a power source.<br>As renewable energy prices continue to fall, however,Professor Moslener said government subsidies are likely to become less and less important.<hr>Which of the following word is most similar in meaning to<b> “plummets”</b> as given in the passage?  ", 
                    " Direction (Set of 6): Given below is a paragraph consisting of blanks against each number. Identify the correct option among the five alternatives that perfectly fits into the given blank against the respective number to make the paragraph contextually meaningful and grammatically correct. <br><br>On October 29, 1929, Black Tuesday hit Wall Street as investors ___ (8) ____some 16 million shares on the New York Stock Exchange in a single day. Billions of dollars were lost, ____ (9) ______out thousands of investors. In the aftermath of Black Tuesday, America and the rest of the industrialized world ___ (10) ______downward into the Great Depression (1929-39), the deepest and longest- lasting economic ______ (11) _____in the history of the Western industrialized world up to that time. During the 1920s, the U.S. stock market underwent rapid expansion, reaching its peak in August 1929, after a period of wild speculation. By then, production had already declined and unemployment had risen, leaving stocks in great excess of their real value. Among the other causes of the eventual market collapse were low wages, the _______ (12) _____ of debt, a struggling agricultural sector and an excess of large bank loans that could not be liquidated. Stock prices began to decline in September and early October 1929, and on October 18 the fall began. Panic set in, and on October 24, Black Thursday, a record 12,894,650 shares were traded. Investment companies and leading bankers attempted to ______ (13) _____ the market by buying up great blocks of stock, producing a moderate rally on Friday.  ",
                    " <br>On October 29, 1929, Black Tuesday hit Wall Street as investors ___ (8) ____some 16 million shares on the New York Stock Exchange in a single day. Billions of dollars were lost, ____ (9) ______out thousands of investors. In the aftermath of Black Tuesday, America and the rest of the industrialized world ___ (10) ______downward into the Great Depression (1929-39), the deepest and longest- lasting economic ______ (11) _____in the history of the Western industrialized world up to that time. During the 1920s, the U.S. stock market underwent rapid expansion, reaching its peak in August 1929, after a period of wild speculation. By then, production had already declined and unemployment had risen, leaving stocks in great excess of their real value. Among the other causes of the eventual market collapse were low wages, the _______ (12) _____ of debt, a struggling agricultural sector and an excess of large bank loans that could not be liquidated. Stock prices began to decline in September and early October 1929, and on October 18 the fall began. Panic set in, and on October 24, Black Thursday, a record 12,894,650 shares were traded. Investment companies and leading bankers attempted to ______ (13) _____ the market by buying up great blocks of stock, producing a moderate rally on Friday.  ",
                    " <br>On October 29, 1929, Black Tuesday hit Wall Street as investors ___ (8) ____some 16 million shares on the New York Stock Exchange in a single day. Billions of dollars were lost, ____ (9) ______out thousands of investors. In the aftermath of Black Tuesday, America and the rest of the industrialized world ___ (10) ______downward into the Great Depression (1929-39), the deepest and longest- lasting economic ______ (11) _____in the history of the Western industrialized world up to that time. During the 1920s, the U.S. stock market underwent rapid expansion, reaching its peak in August 1929, after a period of wild speculation. By then, production had already declined and unemployment had risen, leaving stocks in great excess of their real value. Among the other causes of the eventual market collapse were low wages, the _______ (12) _____ of debt, a struggling agricultural sector and an excess of large bank loans that could not be liquidated. Stock prices began to decline in September and early October 1929, and on October 18 the fall began. Panic set in, and on October 24, Black Thursday, a record 12,894,650 shares were traded. Investment companies and leading bankers attempted to ______ (13) _____ the market by buying up great blocks of stock, producing a moderate rally on Friday. ", 
                    "  <br>On October 29, 1929, Black Tuesday hit Wall Street as investors ___ (8) ____some 16 million shares on the New York Stock Exchange in a single day. Billions of dollars were lost, ____ (9) ______out thousands of investors. In the aftermath of Black Tuesday, America and the rest of the industrialized world ___ (10) ______downward into the Great Depression (1929-39), the deepest and longest- lasting economic ______ (11) _____in the history of the Western industrialized world up to that time. During the 1920s, the U.S. stock market underwent rapid expansion, reaching its peak in August 1929, after a period of wild speculation. By then, production had already declined and unemployment had risen, leaving stocks in great excess of their real value. Among the other causes of the eventual market collapse were low wages, the _______ (12) _____ of debt, a struggling agricultural sector and an excess of large bank loans that could not be liquidated. Stock prices began to decline in September and early October 1929, and on October 18 the fall began. Panic set in, and on October 24, Black Thursday, a record 12,894,650 shares were traded. Investment companies and leading bankers attempted to ______ (13) _____ the market by buying up great blocks of stock, producing a moderate rally on Friday. ",
                    "  <br>On October 29, 1929, Black Tuesday hit Wall Street as investors ___ (8) ____some 16 million shares on the New York Stock Exchange in a single day. Billions of dollars were lost, ____ (9) ______out thousands of investors. In the aftermath of Black Tuesday, America and the rest of the industrialized world ___ (10) ______downward into the Great Depression (1929-39), the deepest and longest- lasting economic ______ (11) _____in the history of the Western industrialized world up to that time. During the 1920s, the U.S. stock market underwent rapid expansion, reaching its peak in August 1929, after a period of wild speculation. By then, production had already declined and unemployment had risen, leaving stocks in great excess of their real value. Among the other causes of the eventual market collapse were low wages, the _______ (12) _____ of debt, a struggling agricultural sector and an excess of large bank loans that could not be liquidated. Stock prices began to decline in September and early October 1929, and on October 18 the fall began. Panic set in, and on October 24, Black Thursday, a record 12,894,650 shares were traded. Investment companies and leading bankers attempted to ______ (13) _____ the market by buying up great blocks of stock, producing a moderate rally on Friday. ", 
                    "  <br>On October 29, 1929, Black Tuesday hit Wall Street as investors ___ (8) ____some 16 million shares on the New York Stock Exchange in a single day. Billions of dollars were lost, ____ (9) ______out thousands of investors. In the aftermath of Black Tuesday, America and the rest of the industrialized world ___ (10) ______downward into the Great Depression (1929-39), the deepest and longest- lasting economic ______ (11) _____in the history of the Western industrialized world up to that time. During the 1920s, the U.S. stock market underwent rapid expansion, reaching its peak in August 1929, after a period of wild speculation. By then, production had already declined and unemployment had risen, leaving stocks in great excess of their real value. Among the other causes of the eventual market collapse were low wages, the _______ (12) _____ of debt, a struggling agricultural sector and an excess of large bank loans that could not be liquidated. Stock prices began to decline in September and early October 1929, and on October 18 the fall began. Panic set in, and on October 24, Black Thursday, a record 12,894,650 shares were traded. Investment companies and leading bankers attempted to ______ (13) _____ the market by buying up great blocks of stock, producing a moderate rally on Friday. ",
                    " Direction (84-88): In the questions given below, there is a sentence in which one part is given in bold. The part given in bold, may or may not be grammatically correct. Choose the best alternative among the four given which can replace the part in bold to make the sentence grammatically correct. If the part given in bold is already correct and does not require any replacement, choose option (e), i.e. “No replacement required” as your answer.<hr> The plastic ban introduced by the municipality has been a total failure as there <b>has been no reducing </b>in the usage of polybags.",
                    " As per the directives, the retail prices of both petrol and diesel<b> is revising</b> on a daily basis. (a) have been revising ", 
                    " <b>We got </b>everything ready for all of them long before they arrived. ",
                    " We still have some farm equipment that <b>hasn't been used</b> since my grandfather died. ",
                    " Every officer and every resident of this village is determined <b>to do their best</b> to get better ranking in sanitation index. ", 
                    " Directions (89-93): In each of the questions given below a sentence is given with a blank. The sentence is then followed by five alternatives out of which one will fit the blank. Choose the alternative that will fit the blank most appropriately and make the sentence grammatically and contextually correct. <hr>Administration has taken positive steps to_________ the education system. ",
                    "  Health and education sectors are one of the most_______ sectors in the global market. ",
                    "  She is an aware citizen who has always ___________ to contribute to the progress of the country. ", 
                    "  In the beginning I looked ________ and could not find quite the car I dreamed of. ",   
                    " The RBI has played conservative in ____________ a rate cut of just 25 basis points. ", 
                    " Directions (94-95): In the following questions two columns are given containing three sentences/phrases each. In first column, sentences/phrases are A, B and C and in the second column the sentences/phrases are D, E and F. A sentence/phrase from the first column may or may not connect with another sentence/phrase from the second column to make a grammatically and contextually correct sentence. Each question has five options which display the sequence(s) in which the sentences/phrases can be joined to form a grammatically and contextually correct sentence. Choose the pair(s) which make(s) a grammatically meaningful sentence. <hr> 4. Column (1)</b><br>(A) The rumors of petrol shortage<br>(B) The body of camera makes it<br>(C) There were no surprises<br><b>Column (2)</b><br>(D) Highly resistant for outdoor use.(E) Turned out to be false.(F) The key stakeholders in the economy",
                    "  <b>Column (1)</b><br>(A) As the rain water began to collect in pools on the highway<br>(B) For years, Argentina would dominate in World Cup qualifying matches<br>(C) Many have accused him of being a quiet misogynist<br><b>Column (2)</b>(D) One of the European countries during the late stages of the tournament<br> (E) Recently unearthed letters argue against this belief<br>(F) It began to hamper the flow of traffic ",
                    " Directions (96-100): Read each sentence to find out whether there is any grammatical or idiomatic error in it. The error, if any, will be in one part of the sentence. The number of that part is the answer. If there is ‘No error’, the answer is (e). (Ignore errors of punctuation, if any.)<hr>People have the freedom (a)/ of speech but at the (b)/ same time each of them (c)/ have to remember their fundamental duties (d)/ No error (e) ", 
                    " The number of students (a)/ competing in the event (b)/ has been fallen (c)/ because of the prize money. (d)/ No error. (e) ",
                    "While he used to walk (a)/ along the road, (b)/ a wild and ferocious dog (c)/ knocked him down. (d)/ No error. (e) ",
                    "  Anaya is even willing (a)/ to make Mexico (b)/ one of the first countries to (c)/ introduces a universal basic income. (d) / No error. (e) ", 
                    " There were no surprises (a)/ in the second bimonthly monetary policy (b)/ announcement by the (c)/ Reserve Bank of India. (d)/ No error. (e) "
                    
                   
                    ],
                "options": [ 
  
                  
     ["Only (I)", "Only (II)", "Only (III)", "Both (II) and (III)", "All (I),(II)and(III)"],
    ["Only (I)", "Only (II)", "None", "Both (II) and (III)", "All (I),(II)and(III)"], 
     ["Only (I)", "Only (II)", "Only (III)", "Both (II) and (III)", "All (I),(II)and(III)"], 
      ["As China is increasing the investment in this sector", "As the price of clean energy technology continues to plummet", "As Fossil fuels is the better alternative", "As there are opportunities and potential for Wind and Solar plants in the East and West Nile areas", "None of these"],
     ["Elevate", "Existence", "Erratic", "Diabolic", "Critical"], 
     ["contradict", "contribute", "Devious", "Retrieve", "Categorical"],
      ["Intensify", "Escalate", "Callous", "Slump", "reminiscent"],
      ["Traded", "Invaded", "Segregated", "Daunted", "Halted"],
      ["Affording", "Wiping", "Wanting", "Vacating", "Artificial"], 
     ["Reprimanded", "Embedded", "Spiraled", "Mounted", "Disregarded"],
      ["provided", "Infiltration", "Dismantle", "Downturn", "Diversification"],
     ["Commotion", "impair", "significant", "Proliferation", "renovate"], 
     ["Infirmity", "Credibility", "Stabilize", "Burdened", "Rationalize"], 
    ["is no reduce", "has been no reduction", "have been no reduced", "is not any reduced", "No correction required"],
     ["have been revising", "are revising", "will be revised", "is revise", "No correction required"], 
     ["We had got", "We have got", "We have been got", "We are getting", "No correction required"],
      ["Hasn’t been using", "was using", "are using", "should not have been use", "No correction required"],
      [" to do there best", "to do its best", "to do his best", "to do ones best", "No replacement required"],
    ["Increase", "Devised", "renovated", "revamp", "dispel"], 
     ["benefit", "necessity", "profit", "lucrative", "Importance"],
      ["wished", "admiring", "prepare", "motivating", "stimulate"],
      ["after", "around", "above", "out", "down"], 
     ["introduce", "proposed", "improving", "decrease", "announcing"], 
      ["C-F and A-D", "B-F", "A-F", "C-E", "B-D and A-E"],
      ["C-F", "B-F", "A-F", "C-E", "None of these"], 
     ["A", "B", "C", "D", "E"],
     ["A", "B", "C", "D", "E"],
     ["A", "B", "C", "D", "E"],
     ["A", "B", "C", "D", "E"], 
     ["A", "B", "C", "D", "E"]
  
  
                    ],
                "correctAnswers": [4, 3, 1, 1, 4, 1, 3, 0, 1, 2, 3, 3, 2, 1, 2, 0, 4, 2, 3, 3, 0, 1, 4, 4, 2, 3, 2, 0, 3, 4] 
                // Index of correct answer for each question
            },
            "hi": {
                "questions": [
                    " 1  ", 
                    " 2  ",
                    " 3  ",
                    " 4  ", 
                    " 5  ",
                    " 6  ",
                    " 7  ", 
                    " 8  ",
                    " 9  ",
                    " 10 ", 
                    " 11 ",
                    " 12 ", 
                    " 13 ",
                    " 14 ",
                    " 15 ", 
                    " 16 ",
                    " 17 ",
                    " 18 ", 
                    " 19 ",
                    " 20 ",
                    " 21 ", 
                    " 22 ",   
                    " 23 ", 
                    " 24 ",
                    " 25 ",
                    " 26 ", 
                    " 27 ",
                    " 28 ",
                    " 29 ", 
                    " 30 ",
                    " 31 ",
                    " 32 ",
                    " 33 ",
                    " 34 ",
                    " 35 "
                   ],
                "options": [ 
                
    1 ["A", "B", "C", "D", "E"],
    2 ["A", "B", "C", "D", "E"], 
    3 ["A", "B", "C", "D", "E"], 
    4 ["A", "B", "C", "D", "E"],
    5 ["A", "B", "C", "D", "E"], 
    6 ["A", "B", "C", "D", "E"],
    7 ["A", "B", "C", "D", "E"],
    8 ["A", "B", "C", "D", "E"],
    9 ["A", "B", "C", "D", "E"], 
    10 ["A", "B", "C", "D", "E"],
    11 ["A", "B", "C", "D", "E"],
    12 ["A", "B", "C", "D", "E"], 
    13 ["A", "B", "C", "D", "E"], 
    14 ["A", "B", "C", "D", "E"],
    15 ["A", "B", "C", "D", "E"], 
    16 ["A", "B", "C", "D", "E"],
    17 ["A", "B", "C", "D", "E"],
    18 ["A", "B", "C", "D", "E"],
    19 ["A", "B", "C", "D", "E"], 
    20 ["A", "B", "C", "D", "E"],
    21 ["A", "B", "C", "D", "E"],
    22 ["A", "B", "C", "D", "E"], 
    23 ["A", "B", "C", "D", "E"], 
    24 ["A", "B", "C", "D", "E"],
    25 ["A", "B", "C", "D", "E"], 
    26 ["A", "B", "C", "D", "E"],
    27 ["A", "B", "C", "D", "E"],
    28 ["A", "B", "C", "D", "E"],
    29 ["A", "B", "C", "D", "E"], 
    30 ["A", "B", "C", "D", "E"],
    31 ["A", "B", "C", "D", "E"],
    32 ["A", "B", "C", "D", "E"], 
    33 ["A", "B", "C", "D", "E"], 
    34 ["A", "B", "C", "D", "E"],
    35 ["A", "B", "C", "D", "E"],
                ],
                "correctAnswers": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35] // Index of correct answer for each question
            }
        };

        var ecurrentQuestion = 0;
                
        var ecorrectCount = 0;     localStorage.setItem('ecorrectCount', ecorrectCount);
        
        var ewrongCount = 0;            localStorage.setItem('ewrongCount', ewrongCount);
                      
                      
                var emarks = 0;          localStorage.setItem('emarks', emarks);   
                        
          var ansered = 0;
           var notansered = 0;
         var marked = 0;
                     
                        
                        
                        
        
nextbtton(ecurrentQuestion)
        function changeLanguage() {
    var language = document.getElementById("languageSelect").value;
    var questions = quizData[language].questions;
    var options = quizData[language].options;
    
document.getElementById("questionNumber").innerHTML = + (ecurrentQuestion + 1) ;
    // Display the current question
    document.getElementById("question").innerHTML = questions[ecurrentQuestion];

    // Display the options
    var optionElement = document.getElementById("options");
    optionElement.innerHTML = '';
    var optionLetters = ['A', 'B', 'C', 'D', 'E']; // Array of option letters
    for (var i = 0; i < options[ecurrentQuestion].length; i++) {
        var optionWrapper = document.createElement("div");
        optionWrapper.className = "option-wrapper";

        var optionLetter = document.createElement("span");
        optionLetter.className = "option-letter";
        optionLetter.innerHTML = optionLetters[i] + ". ";
        optionWrapper.appendChild(optionLetter);

        var radio = document.createElement("input");
        radio.type = "radio";
        radio.name = "option";     radio.value = i;
        radio.onclick = checkAnswer; // Add onclick event to each radio button
        optionWrapper.appendChild(radio);

        var label = document.createElement("label");
        label.innerHTML = options[ecurrentQuestion][i];
        optionWrapper.appendChild(label);

        optionElement.appendChild(optionWrapper);
    }
}


        function showNextQuestion() {
            ecurrentQuestion++;
            if (ecurrentQuestion >= quizData.en.questions.length) {
                ecurrentQuestion = 0;
            }
            changeLanguage();
        }

        function showPreviousQuestion() {
            ecurrentQuestion--;
            if (ecurrentQuestion < 0) {
                ecurrentQuestion = quizData.en.questions.length - 1;
            }
            changeLanguage();
        }

        function checkAnswer() {
            var language = document.getElementById("languageSelect").value;
          


            var selectedOption = document.querySelector('input[name="option"]:checked');
            if (selectedOption) {
                var selectedAnswer = parseInt(selectedOption.value);
                var correctAnswer = quizData[language].correctAnswers[ecurrentQuestion];
                if (selectedAnswer === correctAnswer) {
                    selectedOption.nextElementSibling.classList.add("correct"); // Add 'correct' class to the label element
                   
                    
            
                    
                    
                     // Increment the correct count
                } else {
                    selectedOption.nextElementSibling.classList.add("incorrect"); // Add 'incorrect' class to the label element
                  
                    
                                
                     // Increment the wrong count
                }

            } else {
                alert("Please select an option.")
                
            }
        }

        function saveAndNext() {
    var selectedOption = document.querySelector('input[name="option"]:checked');
    if (selectedOption) {
        var language = document.getElementById("languageSelect").value;
        var correctAnswer = quizData[language].correctAnswers[ecurrentQuestion];
        if (parseInt(selectedOption.value) === correctAnswer) {
            selectedOption.nextElementSibling.classList.add("correct");
            ecorrectCount++;
            
              emarks = emarks + 1;
               localStorage.setItem('emarks', emarks);
            localStorage.setItem('ecorrectCount', ecorrectCount);
            
             // Increment the correct count
        } else {
            selectedOption.nextElementSibling.classList.add("incorrect");
            ewrongCount++;
            
              emarks = emarks - 0.25;
               localStorage.setItem('emarks', emarks);
                localStorage.setItem('ewrongCount', ewrongCount);
            
             // Increment the wrong count
        }
    }
    countAnswers();
    showNextQuestion();
    if (selectedOption) {
        selectedOption.checked = false;
    }
    
    checkedopn();
    
}


        function countAnswers() {
            var etotalQuestions = quizData.en.questions.length;
           var eskiped = etotalQuestions - (ecorrectCount + ewrongCount);
            localStorage.setItem('eskiped', eskiped);
        }
        
                
                        
                        
                        
                                                    
 
